-- MySQL Script generated by MySQL Workbench
-- Sun Aug 12 18:17:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IBM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IBM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IBM` DEFAULT CHARACTER SET utf8 ;
USE `IBM` ;

-- -----------------------------------------------------
-- Table `IBM`.`IDType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`IDType` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `initials` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IBM`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`Client` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `mobile` VARCHAR(15) NULL,
  `address` VARCHAR(45) NULL,
  `identificationNumber` INT(11) NOT NULL,
  `IDType_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `IDType_id`),
  INDEX `fk_Client_IDType_idx` (`IDType_id` ASC),
  UNIQUE INDEX `identificationNumber_UNIQUE` (`identificationNumber` ASC),
  CONSTRAINT `fk_Client_IDType`
    FOREIGN KEY (`IDType_id`)
    REFERENCES `IBM`.`IDType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IBM`.`TypeClothes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`TypeClothes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IBM`.`Clothes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`Clothes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `image` LONGTEXT NULL,
  `typeImage` VARCHAR(45) NULL,
  `sizeImage` VARCHAR(45) NULL,
  `price` INT(11) NOT NULL,
  `TypeClothes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `TypeClothes_id`),
  INDEX `fk_Clothes_TypeClothes1_idx` (`TypeClothes_id` ASC),
  CONSTRAINT `fk_Clothes_TypeClothes1`
    FOREIGN KEY (`TypeClothes_id`)
    REFERENCES `IBM`.`TypeClothes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IBM`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`State` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IBM`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`City` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shippingCost` DOUBLE NOT NULL,
  `State_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `State_id`),
  INDEX `fk_City_State1_idx` (`State_id` ASC),
  CONSTRAINT `fk_City_State1`
    FOREIGN KEY (`State_id`)
    REFERENCES `IBM`.`State` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IBM`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`Order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dateTimeRegistration` VARCHAR(45) NOT NULL,
  `deliveryAddress` VARCHAR(45) NOT NULL,
  `deliveryDate` VARCHAR(45) NOT NULL,
  `Client_id` INT(11) NOT NULL,
  `City_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Client_id`, `City_id`),
  INDEX `fk_Order_Client1_idx` (`Client_id` ASC),
  INDEX `fk_Order_City1_idx` (`City_id` ASC),
  CONSTRAINT `fk_Order_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `IBM`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_City1`
    FOREIGN KEY (`City_id`)
    REFERENCES `IBM`.`City` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IBM`.`Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`Size` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `size` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IBM`.`Order_has_Clothes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`Order_has_Clothes` (
  `Order_id` INT(11) NOT NULL,
  `Clothes_id` INT(11) NOT NULL,
  `Size_id` INT(11) NOT NULL,
  `quantity` INT(1) NOT NULL,
  PRIMARY KEY (`Order_id`, `Clothes_id`, `Size_id`),
  INDEX `fk_Order_has_Clothes_Clothes1_idx` (`Clothes_id` ASC),
  INDEX `fk_Order_has_Clothes_Order1_idx` (`Order_id` ASC),
  INDEX `fk_Order_has_Clothes_Size1_idx` (`Size_id` ASC),
  CONSTRAINT `fk_Order_has_Clothes_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `IBM`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Clothes_Clothes1`
    FOREIGN KEY (`Clothes_id`)
    REFERENCES `IBM`.`Clothes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Clothes_Size1`
    FOREIGN KEY (`Size_id`)
    REFERENCES `IBM`.`Size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
